# Assegna l'autore come assignee
addAssignees: author

# Aggiungi reviewer automaticamente
addReviewers: true

# Lista dei reviewer da assegnare
reviewers:
  - dommy1989
  - gaglileo

# Numero di assignee da aggiungere (0 = tutti)
numberOfAssignees: 1

# Escludi PR in draft (default: false)
runOnDraft: false
